### ISSUE TITLE
ArduinoJson.h is not included in the directory

### ISSUE THREAD

**Issue by kelechiokwuriki** [carrascoacd/ArduinoSIM800L#6]
While trying to compile the HttpExample, the Arduino IDE threw up an error

HttpExample.ino:1:25: fatal error: ArduinoJson.h: No such file or directory

**Comment by carrascoacd** [comment]
Hi kelechi,

The HttpExample is using the ArduinoJson library to manipulate json data.
Try removing the code that is using the library and the include
ArduinoJson.h
Or just download and import the library in your IDE.

Notice, the example probably will not work for you as is the code I am
using in my project. Use it as a guide or example and copy what you need.

Thanks!

On 17 Apr 2017 4:03 p.m., "kelechi okwuriki" <notifications@github.com>
wrote:

While trying to compile the HttpExample, the Arduino IDE threw up an error

HttpExample.ino:1:25: fatal error: ArduinoJson.h: No such file or directory

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/carrascoacd/ArduinoSIM800L/issues/6>, or mute the thread
